### ISSUE TITLE
odmfuse.sh

### ISSUE THREAD

**Issue by arrow53** [Trellis-Logic/secureboot-tegra#1]
@dwalkes this looks like a very useful set of scripts. I'm trying to figure out the status of my fuses on my xavier nx. It seems I can use odmfuse.sh for this. I have no idea where to get this script. I'm using meta-tegra and was thinking it may be part of the `tegraflash.tar.gz`. Is there another place I can look?

**Comment by dwalkes** [comment]
@arrow53 I don't remember, but the last time I ran this it all downloaded and exracted from the scripts here, starting with https://github.com/Trellis-Logic/secureboot-tegra/blob/master/download-and-prepare-files.sh

Based on https://github.com/Trellis-Logic/secureboot-tegra/blob/master/installing-secureboot.sh I think it was in the `SECUREBOOT_PACKAGE` which was https://github.com/Trellis-Logic/secureboot-tegra/blob/master/download-and-prepare-files.sh#L11 and https://github.com/Trellis-Logic/secureboot-tegra/blob/master/downloadfilenames#L4
`secureboot_R32.2.1_aarch64.tbz2`

See the links at the top of each script, they are just attempting to automate the steps in the instructions referenced.

**Comment by arrow53** [comment]
yep. Was the secureboot package. Your memory is great!
